# Generated by Django 4.2.2 on 2023-06-09 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='categorytype',
            field=models.CharField(choices=[('income', 'INCOME'), ('expense', 'EXPENSE')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
