# Generated by Django 4.2.2 on 2023-06-11 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_transaction_type_category_categorytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(default='2023-06-11'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default='2023-06-11'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default='2023-06-11'),
        ),
    ]
