# Generated by Django 4.2.2 on 2023-06-12 03:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_budget_name_alter_budget_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialgoal',
            name='target_date',
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='budget',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='finance.budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(default='2023-06-12'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default='2023-06-12'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default='2023-06-12'),
        ),
    ]
